# Site settings
title: JSON Community
email: comments@bigbluehat.com
description: > # this means to ignore newlines until "baseurl:"
  JSON.com is a collection of JSON related content, links, and general
  awesomeness hand selected by the good people of the Web. The original
  json.com site has been
  <a href="http://web.archive.org/web/20150503020228/https://www.json.com/">
  archived</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: json-com
github_username:  json-com
paginate: 5

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Build settings
markdown: kramdown
gems:
  - jemoji
  - jekyll-redirect-from
