# Site settings
title: JSON Community
email: comments@bigbluehat.com
description: > # this means to ignore newlines until "baseurl:"
  JSON.com is a collection of JSON related content, links, and general
  awesomeness hand selected by the good people of the Web. The original
  json.com site has been
  <a href="http://web.archive.org/web/20150503020228/https://www.json.com/">
  archived</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: json-com
github_username:  json-com
paginate: 5

# Build settings
markdown: kramdown
gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-paginate

# Jekyll Archive Specific stuff
jekyll-archives:
  enabled:
    - year
    - month
    - day
    - tag
    - category
  layouts:
    year: archive-year
    month: archive-month
    day: archive-day
    tag: archive-tag
    category: archive-category
  permalinks:
    year: '/archives/:year/'
    month: '/archives/:year/:month/'
    day: '/archives/:year/:month/:day/'
    tag: '/archives/tag/:name/'
    category: '/archives/category/:name/'
